blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/Daytona39264/Daytona39264/blob/main/.github/ISSUES.md
    about: Please review our contribution guidelines before creating an issue.
